FROM python:3.11.5-slim-bookworm

WORKDIR /app

COPY ./webapi/requirements.txt ./

RUN python -m pip install --no-cache-dir -r requirements.txt

COPY ./webapi ./webapi

CMD ["python", "-m", "webapi.rabbit_server"]