FROM python:3.10

WORKDIR /app

RUN --mount=type=cache,target=/root/.cache/pip \
python -m pip install torch --index-url https://download.pytorch.org/whl/cu121

COPY ./nnmodel/requirements.txt ./

RUN --mount=type=cache,target=/root/.cache/pip \
python -m pip install -r requirements.txt

COPY ./nnmodel ./nnmodel

CMD ["python", "-m", "nnmodel.main"]